### ISSUE TITLE
Following posted guide yields errors.

### ISSUE THREAD

**Issue by marky291** [artisanry/reportable#18]
<img width="1055" alt="Screenshot 2019-06-03 at 16 02 00" src="https://user-images.githubusercontent.com/5384515/58812076-fb99ab80-8618-11e9-9ff9-dcdf48d18979.png">

**Comment by faustbrian** [comment]
https://github.com/artisanry/reportable/releases/tag/3.1.1

**Comment by marky291** [comment]
Thank you @faustbrian for the update and thank you for the package. Works great.
