### ISSUE TITLE
Namespacing broken on namechange

### ISSUE THREAD

**Issue by marky291** [artisanry/reportable#24]
I believe namespacing has become incorrect for your package and now no longer works.
"namespace BrianFaust\Reportable" but package is now "namespace artisanry/reportable"

Also broke my extension class. (usage import of ur package cannot be found)
<img width="554" alt="Screenshot 2019-06-06 at 19 22 28" src="https://user-images.githubusercontent.com/5384515/59056653-96e88600-8890-11e9-8187-5fca51762559.png">

**Comment by marky291** [comment]
"BrianFaust\Reportable\Traits\HasReports" was found in both "/Users/markhester/Documents/Websites/ragnaranks/vendor/artisanry/reportable/src/Traits/HasReports.php" and "/Users/markhester/Documents/Websites/ragnaranks/vendor/faustbrian/laravel-reportable/src/Traits/HasReports.php", the first will be used.

was also found on composer update, before I deleted vendor to try reinstall.

**Comment by faustbrian** [comment]
You will have to remove the old package and replace it with `composer require artisanry/reportable`, then replace `BrianFaust` with `Artisanry`.

**Comment by marky291** [comment]
In my project, the artisanry files namespacing was brianfaust, even after deletion and installing, repo here looks fine, i reverted to old repository to avoid the hassle.

**Comment by faustbrian** [comment]
I would recommend to resolve that issue in your project to avoid long-term issues but if it works for you with your fix then all good.
